#pragma once

namespace Liar
{
	// mesh 里 vertex 类型
	enum MeshVertexType
	{
		MESH_VERTEX_TYPE_POSITION = 0,
		MESH_VERTEX_TYPE_POSITION_NORMAL,
		MESH_VERTEX_TYPE_POSITION_NORMAL_COLOR,
		MESH_VERTEX_TYPE_POSITION_NORMAL_TEXTURE,
		MESH_VERTEX_TYPE_POSITION_NORMAL_COLOR_TEXTURE
	};

	// 定义 vertex 类型占用 float 长度
	enum VertexElementFormat
	{
		ELEMENT_FORMAT_VECTOR2 = 2,
		ELEMENT_FORMAT_VECTOR3 = 3,
		ELEMENT_FORMAT_VECTOR4 = 4,
		ELEMENT_FORMAT_QUATERNION = 4
	};

	// 定义 vertex 类型属性
	enum VertexElementAttr
	{
		ELEMENT_ATTR_POSITION = 0,
		ELEMENT_ATTR_NORMAL,
		ELEMENT_ATTR_TEXTURECOORDINATE,
		ELEMENT_ATTR_COLOR,
		ELEMENT_ATTR_ROTATION
	};

	// 定义 vertex 类型占用的 bit
	enum VertexElementSize
	{
		ELEMENT_SIZE_VECTOR2 = 8,
		ELEMENT_SIZE_VECTOR3 = 12,
		ELEMENT_SIZE_VECTOR4 = 16,
		ELEMENT_SIZE_QUATERNION = 16,
		ELEMENT_SIZE_VECTOR3_DOUBLE = 24,
	};
}