#pragma once

namespace Liar
{
	enum VertexElementUsage
	{
		POSITION0 = 0,
		NORMAL0,
		TEXTURECOORDINATE0,
		COLOR0,
		BINORMAL0,
		TANGENT0,
		BONEINDICES0,
		BONEWEIGHT0,
		DEPTH0,
		FOG0,
		POINTSIZE0,
		SAMPLE0,
		TESSELLATEFACTOR0,

		COLOR1,
		NEXTTEXTURECOORDINATE0,
		TEXTURECOORDINATE1,
		NEXTTEXTURECOORDINATE1,

		CORNERTEXTURECOORDINATE0,
		VELOCITY0,
		STARTCOLOR0,
		STARTSIZE,
		AGEADDSCALE0,
		STARTROTATION,
		ENDCOLOR0,
		STARTLIFETIME,
		TIME0,

		SHAPEPOSITIONSTARTLIFETIME,
		DIRECTIONTIME,
		SIZEROTATION0,
		RADIUS0,
		RADIAN0,
		STARTSPEED,
		RANDOM0,
		RANDOM1,
		SIMULATIONWORLDPOSTION,
		SIMULATIONWORLDROTATION,

		TEXTURECOORDINATE0X,
		TEXTURECOORDINATE0X1,
		TEXTURECOORDINATE0Y,
		OFFSETVECTOR
	};
}